development:
  adapter: mysql2
  host: 127.0.0.1
  database: blog_dev
  username: root
  pool: 5
  timeout: 5000

staging:
  adapter: mysql2
  database: blog_staging
  username: root
  pool: 5
  timeout: 5000

smoke:
  adapter: mysql2
  database: blog_smoke
  username: root
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: blog_test
  username: root
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: blog_production
  pool: 5
  timeout: 5000
