development:
  adapter: mysql2
  database: blog_dev
  username: root
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: blog_test
  username: root
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: blog_production
  pool: 5
  timeout: 5000
