posts:
  index:
    meta_description: "Ruby on Rails Developer Blog, problems, solutions, frontend and backend web development"
    meta_title: "palinium.com"
static_pages:
  about:
    meta_description: "About author of palinium.com"
    meta_title: "author of | palinium.com"
